{"name": "Сохдание курьера с уже существующими данными", "status": "failed", "statusDetails": {"message": "AssertionError: Неверное сообщение об ошибке - Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_courier_creation.TestCourierCreation object at 0x000002795B5DF080>\n\n    @allure.title('Сохдание курьера с уже существующими данными')\n    @allure.description('Сохдание курьера с данными идентичными для уже существующего курьера'\n                        'Проверяется код ответа и сообщение об ошибке')\n    def test_create_duplicate_courier(self):\n        new_courier = UserGenerator.register_new_courier_and_return_login_password()\n        payload = {'login': new_courier[0],\n                   'password': new_courier[1],\n                   'first_name': new_courier[2]\n                   }\n        response = requests.post(ApiUrl.CREATE_COURIER_API_URL, data=payload)\n        Assertions.assert_code_status(response, 409)\n>       Assertions.assert_json_value_by_name(response,\n                                             'message',\n                                             'Этот логин уже используется',\n                                             f'Неверное сообщение об ошибке - {response.json()['message']}'\n                                             )\n\ntests\\test_courier_creation.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [409]>, name = 'message', expected_value = 'Этот логин уже используется'\nerror_message = 'Неверное сообщение об ошибке - Этот логин уже используется. Попробуйте другой.'\n\n    @staticmethod\n    @allure.step('Проверка значения в JSON по ключу')\n    def assert_json_value_by_name(response: Response, name, expected_value, error_message):\n        try:\n            response_as_dict = response.json()\n        except json.JSONDecodeError:\n            assert False, f\"Response is not in JSON format. Response text is '{response.text}'\"\n    \n        assert name in response_as_dict, f\"Response JSON does not have key '{name}'\"\n>       assert response_as_dict[name] == expected_value, error_message\nE       AssertionError: Неверное сообщение об ошибке - Этот логин уже используется. Попробуйте другой.\n\nhelpful_classes\\assertions.py:16: AssertionError"}, "description": "Сохдание курьера с данными идентичными для уже существующего курьераПроверяется код ответа и сообщение об ошибке", "steps": [{"name": "Генерируется новый зарегистрированный курьер", "status": "passed", "steps": [{"name": "Генерация произвольной строки", "status": "passed", "parameters": [{"name": "length", "value": "15"}], "start": 1710870527938, "stop": 1710870527938}, {"name": "Генерация произвольной строки", "status": "passed", "parameters": [{"name": "length", "value": "15"}], "start": 1710870527938, "stop": 1710870527938}, {"name": "Генерация произвольной строки", "status": "passed", "parameters": [{"name": "length", "value": "10"}], "start": 1710870527938, "stop": 1710870527938}], "start": 1710870527938, "stop": 1710870528314}, {"name": "Проверка статус-кода ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [409]>"}, {"name": "expected_status_code", "value": "409"}], "start": 1710870528759, "stop": 1710870528759}, {"name": "Проверка значения в JSON по ключу", "status": "failed", "statusDetails": {"message": "AssertionError: Неверное сообщение об ошибке - Этот логин уже используется. Попробуйте другой.\n", "trace": "  File \"C:\\trainings\\yandex_praktikum_git\\Sprint_7\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\trainings\\yandex_praktikum_git\\Sprint_7\\helpful_classes\\assertions.py\", line 16, in assert_json_value_by_name\n    assert response_as_dict[name] == expected_value, error_message\n"}, "parameters": [{"name": "response", "value": "<Response [409]>"}, {"name": "name", "value": "'message'"}, {"name": "expected_value", "value": "'Этот логин уже используется'"}, {"name": "error_message", "value": "'Неверное сообщение об ошибке - Этот логин уже используется. Попробуйте другой.'"}], "start": 1710870528760, "stop": 1710870528760}], "start": 1710870527938, "stop": 1710870528780, "uuid": "7d5f10b4-94c9-4c76-87ae-94585f206e4f", "historyId": "59837c5c08bc86d2e476e34fa9a8709d", "testCaseId": "59837c5c08bc86d2e476e34fa9a8709d", "fullName": "tests.test_courier_creation.TestCourierCreation#test_create_duplicate_courier", "labels": [{"name": "epic", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "LAPTOP-IE2IJGHD"}, {"name": "thread", "value": "4124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}